"""
Task Key Request Page - Users submit an HFI auth key/link with a task name.
Approvers review the request, see requester details, and provide a response key on approval.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import streamlit as st

from src.infrastructure.database import (
    init_db,
    get_user_by_id,
    can_approve,
    create_task,
    get_next_task_number,
    create_task_key_request,
    get_task_key_requests_by_user,
    get_pending_task_key_requests,
    approve_task_key_request,
    reject_task_key_request,
)
from src.ui.activity_tracker import get_request_access_context
from src.ui.sidebar import quick_hide, render_sidebar, require_auth

init_db()

st.set_page_config(page_title="Task Key Request", page_icon=":material/vpn_key:", layout="wide")
quick_hide()
render_sidebar()
current_user = require_auth("Task Key Request")

st.title("Task Key Request")

st.markdown("""
**User Flow:** :orange[**1. Request Key**] → 2. Repo Preparation → 3. Step 1 Task Submission → 4. Final Submission

Submit your HFI auth key/link along with a task name. An approver will review and respond with a key you can use.
""")

st.markdown("---")

# =========================
# REQUEST FORM
# =========================

st.subheader("Submit New Request")

with st.form("task_key_form"):
    default_name = f"task_{get_next_task_number()}"
    task_name = st.text_input("Task Name", value=default_name, help="Give your task any name you want")
    project_name = st.text_input("Project Name", help="Name or description of the project")
    local_path = st.text_input("Local Repo Path (optional)", placeholder=r"C:\...\repo")
    auth_key = st.text_area(
        "HFI Auth Key / Link",
        height=100,
        help="Paste the authentication link or key generated by claude-hfi",
    )
    submitted = st.form_submit_button("Submit Request", type="primary")

if submitted:
    if not task_name.strip():
        st.error("Task name is required.")
    elif not project_name.strip():
        st.error("Project name is required.")
    elif not auth_key.strip():
        st.error("Auth key is required.")
    else:
        new_task = create_task(
            name=task_name.strip(),
            issue_id=None,
            local_path=local_path.strip() or None,
            actor_user_id=current_user.id,
            access_context=get_request_access_context(),
        )
        create_task_key_request(
            user_id=current_user.id,
            project_name=project_name.strip(),
            auth_key=auth_key.strip(),
            task_id=new_task.id,
            access_context=get_request_access_context(),
        )
        st.success(f"Task **{new_task.name}** created and key request submitted!")
        st.rerun()

# =========================
# MY REQUESTS
# =========================

st.markdown("---")
st.subheader("My Requests")

my_requests = get_task_key_requests_by_user(current_user.id)
if my_requests:
    for req in my_requests:
        status_color = {"pending": "orange", "approved": "green", "rejected": "red"}.get(req.status, "gray")

        with st.expander(f"{req.project_name} — :{status_color}[{req.status.upper()}] — {req.created_at:%Y-%m-%d %H:%M}"):
            st.text(f"Auth Key Sent: {req.auth_key[:80]}{'...' if len(req.auth_key) > 80 else ''}")

            if req.status == "approved":
                if req.response_key:
                    st.success("Approved! Here is your response key:")
                    st.code(req.response_key, language="text")
                else:
                    st.success("Approved! (No response key was provided)")
                st.page_link("pages/3_Repo_Preparation.py", label="Go to Repo Preparation", icon=":material/build:")
                if req.approved_at:
                    approver = get_user_by_id(req.approved_by) if req.approved_by else None
                    st.caption(f"Approved by {approver.username if approver else 'Unknown'} at {req.approved_at:%Y-%m-%d %H:%M}")
            elif req.status == "rejected":
                st.error(f"Rejected: {req.rejection_reason or 'No reason given'}")
                st.info("You can submit a new request with updated information.")
            elif req.status == "pending":
                st.info("Waiting for approval...")
else:
    st.info("You haven't submitted any task key requests yet.")

# =========================
# PENDING APPROVALS (for approvers)
# =========================

if can_approve(current_user):
    st.markdown("---")
    st.subheader("Pending Approvals")

    pending = get_pending_task_key_requests()
    if pending:
        for p in pending:
            requester = get_user_by_id(p.user_id)
            requester_name = requester.username if requester else "Unknown"

            with st.expander(f"#{p.id} — {p.project_name} — by {requester_name} — {p.created_at:%Y-%m-%d %H:%M}"):
                st.markdown("#### Requester Details")
                if requester:
                    detail_cols = st.columns(3)
                    with detail_cols[0]:
                        st.markdown(f"**Username:** {requester.username}")
                        st.markdown(f"**Email:** {requester.email or 'N/A'}")
                        st.markdown(f"**Role:** {requester.role or 'user'}")
                    with detail_cols[1]:
                        st.markdown(f"**Last IP:** {requester.last_seen_ip or 'N/A'}")
                        st.markdown(f"**Country:** {requester.last_seen_country or 'N/A'}")
                        st.markdown(f"**Location:** {requester.last_seen_location or 'N/A'}")
                    with detail_cols[2]:
                        st.markdown(f"**Device:** {requester.last_seen_device or 'N/A'}")
                        st.markdown(f"**Verified:** {'Yes' if requester.is_verified else 'No'}")
                        if requester.last_active_at:
                            st.markdown(f"**Last Active:** {requester.last_active_at:%Y-%m-%d %H:%M}")
                else:
                    st.warning("Requester user not found.")

                st.markdown("#### Submitted Auth Key")
                st.code(p.auth_key, language="text")

                st.markdown("---")

                col1, col2 = st.columns(2)
                with col1:
                    response_key_input = st.text_area(
                        "Response Key (required to approve)",
                        key=f"resp_key_{p.id}",
                        height=80,
                        help="Provide the key/token that the requester will receive upon approval",
                    )
                    if st.button("Approve", key=f"approve_tkr_{p.id}", type="primary"):
                        if not response_key_input.strip():
                            st.error("You must provide a response key to approve.")
                        else:
                            approve_task_key_request(
                                p.id,
                                current_user.id,
                                response_key=response_key_input.strip(),
                                task_id=p.task_id,
                                access_context=get_request_access_context(),
                            )
                            st.success("Approved! Response key sent to requester.")
                            st.rerun()
                with col2:
                    reason = st.text_input("Rejection reason", key=f"rej_tkr_{p.id}")
                    if st.button("Reject", key=f"reject_tkr_{p.id}"):
                        reject_task_key_request(p.id, current_user.id, reason, get_request_access_context())
                        st.warning("Request rejected.")
                        st.rerun()
    else:
        st.info("No pending task key requests.")
