"""
Task Key Request Page - Users paste an HFI auth key linked to a specific task.
Requests must be approved by a role_manager or rebumex before proceeding.

This is STEP 1 of the user flow:
  1. Request Key (here) → 2. Repo Preparation → 3. Model Evaluation → 4. Labeling → 5. Complete
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import streamlit as st

from src.infrastructure.database import (
    init_db,
    get_all_tasks,
    get_task_by_id,
    get_user_by_id,
    can_approve,
    create_task,
    get_next_task_number,
    create_task_key_request,
    get_task_key_requests_by_user,
    get_pending_task_key_requests,
    approve_task_key_request,
    reject_task_key_request,
    get_key_request_for_task,
)
from src.ui.activity_tracker import get_request_access_context
from src.ui.sidebar import quick_hide, render_sidebar, require_auth

init_db()

st.set_page_config(page_title="Task Key Request", page_icon=":material/vpn_key:", layout="wide")
quick_hide()
render_sidebar()
current_user = require_auth("Task Key Request")

st.title("Task Key Request")

# =========================
# FLOW PROGRESS
# =========================

st.markdown("""
**User Flow:** :orange[**1. Request Key**] → 2. Repo Preparation → 3. Model Evaluation → 4. Labeling → 5. Complete

Paste your HFI auth key/link and link it to the task you're starting. A role manager or admin will approve your request.
""")

st.markdown("---")

# =========================
# REQUEST FORM
# =========================

st.subheader("Submit New Request")

tasks = get_all_tasks()

# Filter to tasks that don't already have an approved/pending key
tasks_without_key = []
for t in tasks:
    existing = get_key_request_for_task(t.id)
    if not existing or existing.status == "rejected":
        tasks_without_key.append(t)

create_new_task = st.toggle("Create a new task", value=len(tasks_without_key) == 0,
                            help="Create a standalone task without using Issue Finder")

if create_new_task:
    with st.form("new_task_form"):
        default_name = f"task_{get_next_task_number()}"
        task_name = st.text_input("Task Name", value=default_name)
        local_path = st.text_input("Local Repo Path (optional)", placeholder=r"C:\...\repo")
        project_name = st.text_input("Project Name", help="Name or description of the project")
        auth_key = st.text_area("HFI Auth Key / Link", height=100,
                                help="Paste the authentication link or key generated by claude-hfi")
        submitted = st.form_submit_button("Create Task & Submit Request", type="primary")

    if submitted:
        if not task_name:
            st.error("Task name is required.")
        elif not project_name:
            st.error("Project name is required.")
        elif not auth_key:
            st.error("Auth key is required.")
        else:
            new_task = create_task(
                name=task_name,
                issue_id=None,
                local_path=local_path or None,
                actor_user_id=current_user.id,
                access_context=get_request_access_context(),
            )
            create_task_key_request(
                user_id=current_user.id,
                project_name=project_name,
                auth_key=auth_key.strip(),
                task_id=new_task.id,
                access_context=get_request_access_context(),
            )
            st.success(f"Task **{new_task.name}** created and key request submitted!")
            st.rerun()
else:
    with st.form("task_key_form"):
        if tasks_without_key:
            task_options = {t.id: f"{t.name} ({t.status})" for t in tasks_without_key}
            selected_task_id = st.selectbox(
                "Link to Task",
                list(task_options.keys()),
                format_func=lambda x: task_options[x],
            )
        else:
            st.info("All existing tasks already have key requests. Toggle 'Create a new task' above to start fresh.")
            selected_task_id = None

        project_name = st.text_input("Project Name", help="Name or description of the project you're working on")
        auth_key = st.text_area("HFI Auth Key / Link", height=100,
                                help="Paste the authentication link or key generated by claude-hfi")
        submitted = st.form_submit_button("Submit Request", type="primary")

    if submitted:
        if not selected_task_id:
            st.error("No task available to link.")
        elif not project_name:
            st.error("Project name is required.")
        elif not auth_key:
            st.error("Auth key is required.")
        else:
            create_task_key_request(
                user_id=current_user.id,
                project_name=project_name,
                auth_key=auth_key.strip(),
                task_id=selected_task_id,
                access_context=get_request_access_context(),
            )
            st.success("Request submitted! Waiting for manager approval.")
            st.rerun()

# =========================
# MY REQUESTS
# =========================

st.markdown("---")
st.subheader("My Requests")

my_requests = get_task_key_requests_by_user(current_user.id)
if my_requests:
    for req in my_requests:
        status_color = {"pending": "orange", "approved": "green", "rejected": "red"}.get(req.status, "gray")
        linked_task = get_task_by_id(req.task_id) if req.task_id else None
        task_label = f" → Task: {linked_task.name}" if linked_task else ""

        with st.expander(f"{req.project_name}{task_label} — :{status_color}[{req.status.upper()}] — {req.created_at:%Y-%m-%d %H:%M}"):
            st.text(f"Auth Key: {req.auth_key[:80]}{'...' if len(req.auth_key) > 80 else ''}")

            if req.status == "approved":
                st.success("Approved! Proceed to Repo Preparation.")
                st.page_link("pages/3_Repo_Preparation.py", label="Go to Repo Preparation", icon=":material/build:")
                if req.approved_at:
                    approver = get_user_by_id(req.approved_by) if req.approved_by else None
                    st.caption(f"Approved by {approver.username if approver else 'Unknown'} at {req.approved_at:%Y-%m-%d %H:%M}")
            elif req.status == "rejected":
                st.error(f"Rejected: {req.rejection_reason or 'No reason given'}")
                st.info("You can submit a new request with updated information.")
            elif req.status == "pending":
                st.info("Waiting for manager approval...")
else:
    st.info("You haven't submitted any task key requests yet.")

# =========================
# PENDING APPROVALS (for role_manager / rebumex)
# =========================

if can_approve(current_user):
    st.markdown("---")
    st.subheader("Pending Approvals")

    pending = get_pending_task_key_requests()
    if pending:
        for p in pending:
            requester = get_user_by_id(p.user_id)
            requester_name = requester.username if requester else "Unknown"
            linked_task = get_task_by_id(p.task_id) if p.task_id else None

            with st.expander(f"#{p.id} — {p.project_name} — by {requester_name} — {p.created_at:%Y-%m-%d %H:%M}"):
                st.text(f"Auth Key:\n{p.auth_key}")
                if linked_task:
                    st.caption(f"Linked to task: **{linked_task.name}** (status: {linked_task.status})")

                col1, col2 = st.columns(2)
                with col1:
                    if st.button("Approve", key=f"approve_tkr_{p.id}", type="primary"):
                        approve_task_key_request(
                            p.id, current_user.id,
                            task_id=p.task_id,
                            access_context=get_request_access_context(),
                        )
                        st.success(f"Approved! Auth key linked to task.")
                        st.rerun()
                with col2:
                    reason = st.text_input("Rejection reason", key=f"rej_tkr_{p.id}")
                    if st.button("Reject", key=f"reject_tkr_{p.id}"):
                        reject_task_key_request(p.id, current_user.id, reason, get_request_access_context())
                        st.warning("Request rejected.")
                        st.rerun()
    else:
        st.info("No pending task key requests.")
